export const ROLES = {
  SYS_ADMIN: "SYS_ADMIN",
  PLANIFICATION_TECHNICIAN: "PLANIFICATION_TECHNICIAN",
  INSTITUTIONAL_REVIEWER: "INSTITUTIONAL_REVIEWER",
  VALIDATING_AUTHORITY: "VALIDATING_AUTHORITY",
};
