export enum ProjectStatusEnum {
  ACTIVE = "ACTIVE",
  SEND_FOR_APPROVAL = "SEND_FOR_APPROVAL",
  INACTIVE = "INACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  ON_HOLD = "ON_HOLD",
  REJECTED = "REJECTED",
  APPROVED = "APPROVED",
  REQUEST_CHANGES = "REQUEST_CHANGES",
}
